### ISSUE TITLE
bug: multiple friends with the same person

### ISSUE THREAD

**Issue by sam574** [guiomie/workoutcell#12]

**Comment by guiomie** [comment]
Noticed this a while ago, then forgot about it, will fix tonight.

**Comment by guiomie** [comment]
Fixed in dev environment. A user can't add someone already a friend, he cant send a request to someone already a friend, and he can't add himself as a friend. Will need to confirm in production on next release.

**Comment by guiomie** [comment]
Confirmed has  fixed in release v0.3.
